name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
author: ${project.organization.name}
api-version: 1.13
commands:
  customcompass:
    description: Main Custom Compass command
    permission: customcompass.cmd.main
    aliases: [cc]