name: ${project.artifactId}
main: ${project.groupId}.Main
version: ${project.version}
author: ${project.organization.name}
api-version: 1.13
commands:
  customcompass:
    description: Main Custom Compass command
    permission: customcompass.cmd.main
  cc:
    description: Main Custom Compass command (short version)
    permission: customcompass.cmd.main